//
//  SinglePortfolioView.swift
//  Photo Club Hub
//
//  Created by Peter van den Hamer on 03/01/2022.
//

import SwiftUI
import WebKit // for UIViewRepresentable protocol and WKWebView

// There will be multiple MemberViews?
struct SinglePortfolioView: UIViewRepresentable {

    @State var url: URL
    // wrapper from UIKit to a SwiftUI view
    typealias UIViewType = WKWebView
    @State var webView: WKWebView // sharing WKWebView to avoid error messages if webView goes out of scope

    /// Screenshot pipeline (#777): 1-based index of the gallery image to jump to after the page loads.
    /// Non-nil only when the app was launched with `-initialTab PortfolioViaClubs`; nil in normal use,
    /// which leaves the web view completely untouched (no injected script, no navigation delegate).
    var presetImageIndex: Int?

    func makeCoordinator() -> ScreenshotCoordinator {
        ScreenshotCoordinator(presetImageIndex: presetImageIndex)
    }

    func makeUIView(context: Context) -> WKWebView {
        if presetImageIndex != nil {
            installJuiceboxTrap()
            webView.navigationDelegate = context.coordinator
        }
        return webView
    }

    func updateUIView(_ uiView: WKWebView, context: Context) {
        webView.load(URLRequest(url: url))
    }

    /// Injects a script (at document start, before the site's own scripts run) that captures the
    /// Juicebox-Pro gallery instance the page creates, exposing it as `window.__jbInstance` (#777).
    ///
    /// The trap is inert on portfolio sites not generated by Juicebox-Pro: it merely defines a
    /// `window.juicebox` property and waits, and it wraps the assigned value only if that value is a
    /// constructor function. Everything lives app-side; the licensed Juicebox-Pro files (HTML/JS)
    /// are not modified. Worst case on a foreign site: the screenshot shows that site's opening screen.
    private func installJuiceboxTrap() {
        let controller = webView.configuration.userContentController
        // the WKWebView is shared and makeUIView can run more than once: install the trap only once
        guard !controller.userScripts.contains(where: { $0.source.contains("__jbInstance") }) else { return }
        controller.addUserScript(WKUserScript(source: Self.juiceboxTrapScript,
                                              injectionTime: .atDocumentStart,
                                              forMainFrameOnly: true))
    }

    private static let juiceboxTrapScript = """
        (function () {
            'use strict';
            var captured;
            Object.defineProperty(window, 'juicebox', {
                configurable: true,
                get: function () { return captured; },
                set: function (value) {
                    if (typeof value === 'function') {
                        captured = new Proxy(value, {
                            construct: function (target, args) {
                                var instance = Reflect.construct(target, args);
                                window.__jbInstance = instance;
                                return instance;
                            }
                        });
                    } else {
                        captured = value; // an unrelated `juicebox` global: pass through unchanged
                    }
                }
            });
        })();
        """

    /// In screenshot mode (#777), waits for the Juicebox gallery to come alive after `didFinish`
    /// (gallery construction and image loading continue asynchronously), then jumps it to
    /// `presetImageIndex`. All JavaScript is guarded, so the polling quietly times out on
    /// non-Juicebox sites without affecting what they display.
    final class ScreenshotCoordinator: NSObject, WKNavigationDelegate {

        private let presetImageIndex: Int?

        init(presetImageIndex: Int?) {
            self.presetImageIndex = presetImageIndex
        }

        func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
            guard let presetImageIndex else { return }
            let jumpScript = """
                (function () {
                    var jb = window.__jbInstance;
                    if (!jb || typeof jb.showImage !== 'function') { return 'pending'; }
                    var index = (typeof jb.getImageIndex === 'function') ? jb.getImageIndex() : -1;
                    if (index !== \(presetImageIndex)) { jb.showImage(\(presetImageIndex)); }
                    return String(index);
                })();
                """
            Task { @MainActor in
                for _ in 0..<20 { // poll for up to ~10 s; times out harmlessly on non-Juicebox sites
                    let result = try? await webView.evaluateJavaScript(jumpScript)
                    if let index = result as? String, index == String(presetImageIndex) { return }
                    try? await Task.sleep(for: .milliseconds(500))
                }
            }
        }

    }

}

// MARK: - Previews

// only visible when canvas is simulating/running (?)
// Believe it or not, this preview actually works.
struct SinglePortfolioView_Previews: PreviewProvider {

    static var webView = WKWebView()
    static var url: URL = URL(string: "http://www.vdHamer.com/fgWaalre/Peter_van_den_Hamer/")!

    static var previews: some View {
        NavigationStack {
            SinglePortfolioView(url: url, webView: webView)
                .previewLayout(.sizeThatFits)
                .navigationBarTitle(String("SinglePortfolioView")) // avoid localization
                .navigationBarTitleDisplayMode(.large)
        }
    }

}
