//
//  SinglePortfolioView+Screenshot.swift
//  Photo Club Hub
//
//  Created by Peter van den Hamer on 17/07/2026.
//

import WebKit // for WKWebView, WKUserScript, WKNavigationDelegate

// Screenshot pipeline only (#777) — no role in normal app use.
// Kept out of SinglePortfolioView.swift so the mainstream code stays uncluttered. The
// counterpart stored property (`presetImageIndex`) remains in SinglePortfolioView itself;
// it is nil in normal use, which makes everything in this file a no-op.
extension SinglePortfolioView {

    /// Called from `makeUIView`. In normal use (`presetImageIndex == nil`) this does nothing,
    /// leaving the web view completely untouched: no injected script, no navigation delegate.
    func configureForScreenshotCapture(context: Context) {
        guard presetImageIndex != nil else { return }
        installJuiceboxTrap()
        webView.navigationDelegate = context.coordinator
    }

    func makeCoordinator() -> ScreenshotCoordinator {
        ScreenshotCoordinator(presetImageIndex: presetImageIndex)
    }

    /// Injects a script (at document start, before the site's own scripts run) that captures the
    /// Juicebox-Pro gallery instance the page creates, exposing it as `window.__jbInstance` (#777).
    ///
    /// The trap is inert on portfolio sites not generated by Juicebox-Pro: it merely defines a
    /// `window.juicebox` property and waits, and it wraps the assigned value only if that value is a
    /// constructor function. Everything lives app-side; the licensed Juicebox-Pro files (HTML/JS)
    /// are not modified. Worst case on a foreign site: the screenshot shows that site's opening screen.
    private func installJuiceboxTrap() {
        let controller = webView.configuration.userContentController
        // the WKWebView is shared and makeUIView can run more than once: install the trap only once
        guard !controller.userScripts.contains(where: { $0.source.contains("__jbInstance") }) else { return }
        controller.addUserScript(WKUserScript(source: Self.juiceboxTrapScript,
                                              injectionTime: .atDocumentStart,
                                              forMainFrameOnly: true))
    }

    private static let juiceboxTrapScript = """
        (function () {
            'use strict';
            var captured;
            Object.defineProperty(window, 'juicebox', {
                configurable: true,
                get: function () { return captured; },
                set: function (value) {
                    if (typeof value === 'function') {
                        captured = new Proxy(value, {
                            construct: function (target, args) {
                                var instance = Reflect.construct(target, args);
                                window.__jbInstance = instance;
                                return instance;
                            }
                        });
                    } else {
                        captured = value; // an unrelated `juicebox` global: pass through unchanged
                    }
                }
            });
        })();
        """

    /// In screenshot mode (#777), waits for the Juicebox gallery to come alive after `didFinish`
    /// (gallery construction and image loading continue asynchronously), then jumps it to
    /// `presetImageIndex`. All JavaScript is guarded, so the polling quietly times out on
    /// non-Juicebox sites without affecting what they display.
    final class ScreenshotCoordinator: NSObject, WKNavigationDelegate {

        private let presetImageIndex: Int?

        init(presetImageIndex: Int?) {
            self.presetImageIndex = presetImageIndex
        }

        func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
            guard let presetImageIndex else { return }
            let jumpScript = """
                (function () {
                    var jb = window.__jbInstance;
                    if (!jb || typeof jb.showImage !== 'function') { return 'pending'; }
                    var index = (typeof jb.getImageIndex === 'function') ? jb.getImageIndex() : -1;
                    if (index !== \(presetImageIndex)) { jb.showImage(\(presetImageIndex)); }
                    return String(index);
                })();
                """
            Task { @MainActor in
                // Signal readiness (#776) both on success and after the timeout: on a
                // non-Juicebox site the capture then simply shows that site's opening screen.
                defer { ScreenshotReadiness.signalReady(for: "PortfolioViaClubs") }
                for _ in 0..<20 { // poll for up to ~10 s; times out harmlessly on non-Juicebox sites
                    let result = try? await webView.evaluateJavaScript(jumpScript)
                    if let index = result as? String, index == String(presetImageIndex) { return }
                    try? await Task.sleep(for: .milliseconds(500))
                }
            }
        }

    }

}
